### ISSUE TITLE
Search is too rigid: allow accent-insensitive search queries

### ISSUE THREAD

**Issue by JaimeObregon** [the-paperless-project/paperless#115]
We are all used to "google-like" search, where accents and even typos in the query string do not really affect the search results. However Paperless seems to be a little bit too rigid when it comes to search. For instance, `Zürich` or `Telefónica` doesn't match `Zurich` and `Telefonica`, a behaviour which can frustrate some searches.

It looks like this can be achieved with the current SQLite backend by [providing some conversion tables](http://www.sqlite.org/faq.html#q18) that I guess they are so common that they already exist in the open source community. And after a quick look at Stack Overflow I [found](http://stackoverflow.com/questions/26871674/sqlite-custom-accent-collation-function-and-like-queries) [some](http://stackoverflow.com/questions/31331629/implementing-accent-insensitive-search-on-django-using-sqlite) [insight](http://stackoverflow.com/questions/2392732/sqlite-python-unicode-and-non-utf-data) which I hope they help.

**Comment by danielquinn** [comment]
My own searching for a solution rendered a [similar result](https://stackoverflow.com/questions/2240880/django-haystack-search-for-a-term-with-and-without-accents).  Basically, the "simplest" method to work around this problem appears to be to store an ascii-only version of the text in the database parallel to a proper version and then perform searches against that (while also normalising the search query).

Interestingly, this might be a kill-two-birds-with-one-stone situation.  #88 involves rewriting all of the stored records and keeping the white space for readability.  This might be a good time to write that migration if it means simultaneously creating a "search-only" field for data as well.

I'm going to tag this as `enhancement` and get to it when I can.  Currently, I'm fiddling with doing a better UI, which will help out a lot, because sanitising a search query through Django's admin is likely to be a lot harder than simply handling my own form data on the new front-end.

**Comment by danielquinn** [comment]
I just [discovered](https://twitter.com/raymondh/status/756261999328112640?s=09) `.casefold()` which may help in this area.
