### ISSUE TITLE
PDF2PDFPOCR pre-consumption script in Docker?

### ISSUE THREAD

**Issue by murmelbahn** [the-paperless-project/paperless#469]
Hi,
at first i want to thank @danielquinn for this awesome software. Many thanks for sharing and caring this.

I have problems with the example pre-consumption script for pdf2pdfocr from here: https://paperless.readthedocs.io/en/latest/consumption.html#pre-consumption-script
I'm using paperless as docker installation and have mounted a script folder in which I have placed the pre script. The script should start the pdf2pdfocr docker installation with the following statement:

docker run --rm -v "$(pwd):/home/docker" leofcardoso/pdf2pdfocr -v -i ${1}

But the script is aborted with the message:
docker: command not found

I think its because the docker installation of Paperless didnt know anything about docker but I dont know how to fix this. Is somebody here which are using this?

Many thanks in advance.

**Comment by khrise** [comment]
Hi, 
the docker container running paperless doesn't know docker - unless you install it there.
I'd recommend to install the command you want to run (along with its dependencies) in the docker image by modifying the docker file and rebuild the image afterwards. Then you can pass in a script which runs this command. 
In my case, I'm running `ocrmypdf` as preconsumption script (since I want the ocr'ed text to be persisted in the pdf file, too).
My Dockerfile modifications look like this (note the red and green lines):
```diff --git a/Dockerfile b/Dockerfile
--- a/Dockerfile
+++ b/Dockerfile
 
-
 RUN apk update --no-cache && apk add python3 gnupg libmagic bash shadow curl \
-        sudo poppler tesseract-ocr imagemagick ghostscript unpaper optipng && \
+        sudo poppler tesseract-ocr imagemagick ghostscript unpaper optipng \ 
+        ocrmypdf jbig2dec && \
     apk add --virtual .build-dependencies \
         python3-dev poppler-dev gcc g++ musl-dev zlib-dev jpeg-dev && \
 # Install python dependencies
@@ -40,6 +41,9 @@ VOLUME ["/usr/src/paperless/data", "/usr/src/paperless/media", "/consume", "/exp
 ENTRYPOINT ["/sbin/docker-entrypoint.sh"]
 CMD ["--help"]
 
+COPY ocr-pdf /usr/local/bin/ocr-pdf.sh
+RUN chmod 755 /usr/local/bin/ocr-pdf.sh
+
 # Copy application
 COPY src/ /usr/src/paperless/src/
 COPY data/ /usr/src/paperless/data/
``` 

The `ocr-pdf` which gets copied to `/usr/local/bin/ocr-pdf.sh` is as simple as:
```
#!/usr/bin/env bash
echo "running ocrmypdf"
ocrmypdf -v1 --output-type pdf -l deu "${1}" "${1}"
```
I hope this gets you started.
Regards, khrise

**Comment by danielquinn** [comment]
This issue is pretty old with now updates, so I'm going to close it for now.  If there's new developments, feel free to re-open.
