### ISSUE TITLE
breakdown / clarification for python requirements.txt

### ISSUE THREAD

**Issue by mtonnie** [the-paperless-project/paperless#555]
Is there any documentation or possibility to enhance python dependeny / requirements management.
Currently it seems that there ist no difference between python packages which are required for paperless itslef, documentation build, test, ....

I need to know which requirements are really needed to run paperless, because I try to create a package for synology nas.

I would really apricate to get some clarification on this point, if possible separate requirements.txt files would be greate, comments are welcome as well.

Thanks in advance

**Comment by danielquinn** [comment]
It's true, that's not entirely obvious, even from the `Pipfile` which is supposed to do a better job of that.  I'll try to do so here.

This is the contents of the Pipfile:

```
django = "<2.1,>=2.0"
pillow = "*"
coveralls = "*"
dateparser = "*"
django-cors-headers = "*"
django-crispy-forms = "*"
django-extensions = "*"
django-filter = "*"
djangorestframework = "*"
factory-boy = "*"
filemagic = "*"
fuzzywuzzy = {extras = ["speedup"], version = "==0.15.0"}
gunicorn = "*"
inotify-simple = "*"
langdetect = "*"
pdftotext = "*"
pyocr = "*"
python-dateutil = "*"
python-dotenv = "*"
python-gnupg = "*"
pytz = "*"
sphinx = "*"
tox = "*"
pycodestyle = "*"
pytest = "*"
pytest-cov = "*"
pytest-django = "*"
pytest-sugar = "*"
pytest-env = "*"
pytest-xdist = "*"
psycopg2 = "*"
djangoql = "*"
```

Of those, anything starting with `pytest-*` is only used to run the tests, so you probably won't need those for a Synology package.  Similarly, `tox` is used for tests, so you don't need that.  `coveralls` can also go.

You *should* be ok removing `factory-boy`, but I'm not 100% on that.

`sphinx` is used for documentation generation, so you don't need that either, and finally, `pycodestyle` is used to enforce a coding standard, so you won't need that just to run the project.

Everything else is required, so that brings us to:

```
django = "<2.1,>=2.0"
pillow = "*"
dateparser = "*"
django-cors-headers = "*"
django-crispy-forms = "*"
django-extensions = "*"
django-filter = "*"
djangorestframework = "*"
filemagic = "*"
fuzzywuzzy = {extras = ["speedup"], version = "==0.15.0"}
gunicorn = "*"
inotify-simple = "*"
langdetect = "*"
pdftotext = "*"
pyocr = "*"
python-dateutil = "*"
python-dotenv = "*"
python-gnupg = "*"
pytz = "*"
psycopg2 = "*"
djangoql = "*"
```

I hope that helps!

**Comment by diveflo** [comment]
Maybe we could move these dependencies you just mentioned into the [dev-packages] section of the Pipfile.
That way, at least the Pipfile based install will not try to install these.

**Comment by danielquinn** [comment]
I have no objections to that.  I would suggest issuing a PR and citing this conversation.  It shouldn't be too hard to get support from another maintainer to do this.
