### ISSUE TITLE
Document Categories

### ISSUE THREAD

**Issue by nuudles** [the-paperless-project/paperless#58]
Thanks for putting together this tool! After a bit of tooling around, I've got a bare metal install to play with. I was wondering what your thoughts are on creating a new property for Documents for a Category, separate from the tags. That way if you want to separate Documents into "Mail", "Receipts", "Statements", you can do that and perhaps even have different behaviors per Category.

An example of something that I personally would like to see is that for all of my Mail that I scan, I scan the envelope first, then open it up and scan the contents as subsequent pages. It would be cool for the "Mail" category to show a thumbnail of the first page of the PDF (in my case it would be the envelope). For the other Categories, maybe allow the user to upload their own images or whatnot to show for them so that at a glance, the Documents can be quickly gleaned as to which Category they belong to (a briefcase or a lock or whatnot).

If you're not opposed to the idea, I could potentially help implement it, time permitting.

**Comment by the01** [comment]
Isn't that basically like having a "mail", "receipts",... tag?

**Comment by nuudles** [comment]
@the01 Perhaps, but I like the idea of having a category outside of the Tag system and treating each Category differently (like my idea with the thumbnail above). If there's not much interest in the idea, I'll drop it, but I thought it'd be a nice thing to have. It could be optional as well, so if you wanted to stick to only using Tags for organization, you wouldn't need to set a Category.

**Comment by the01** [comment]
Are you thinking of fixed categories to choose from or free-form like the tags?

**Comment by nuudles** [comment]
Free form

**Comment by the01** [comment]
And the difference to tags would be a different document type (model)?

**Comment by the01** [comment]
But if a category is free from, how can you add e.g. thumbnails at runtime? Every document would have to support the thumbnail and not just certan categories. Or you would have to preprogram specific categories that have thumbnails, which would change the feature request to "Document thumbnails"?
Do you know what I am getting at?

**Comment by nuudles** [comment]
A Category is still an object, like a Document or a Tag. So just like a Tag can currently have a specific color associated with it and matching algorithms, a Category can have its own properties, like a thumbnail or a property that tells the Document to use its first page as the thumbnail. It's only "freeform" in that you can create new Categories, rather than having predefined ones to choose from.

**Comment by the01** [comment]
Ah, I think I finally understand where you are coming from! :smile: 
The thought of different behaviour (thumbnail, first page,..) is intriguing, but what if it was combinable? - take your idea and apply it to tags.

Here is what I mean: Lets use your mail example.
You get the water bill and since you scan the envelope, you define that all "mail" tags should show a thumbnail - the first page here.
But now you have another letter, this time from your grandma (or meemaw if you will :wink:). You still give it the mail tag - you want a thumbnail - but additionally you add your meemaw tag. This overwrites the first-page-thumbnail with a nice picture of her.

I'm not sure how one would go about actually implementing that kind of logic, but it would be neat :bowtie:

**Comment by nuudles** [comment]
That might be interesting, but I still think it would be better to have an over-arching "Category" to associate the Documents with. That way it's clear that you categorize the Document as being Mail, or a Tax Document, etc. but you can still tag the Document with whatever Tags you want. It's not a far-fetched idea and there are benefits to categorization be separate. Think about a navigation scheme where rather then getting a list of 50+ tags, you start with your 5 major Categories plus an "All" option so you can drill down right to "Mail" from the start without muddling through a ton of unequally weighted Tags.

**Comment by danielquinn** [comment]
The difficulty with adding a `.category` property is in the maintenance.  I don't want Paperless to require any substantial effort to use once it's set up.  As it is, the `.sender` and `.title` properties are something of a pain because they're spawned from the file name (requires manual effort) or entered via the admin (manual effort).  The tags are nicely automatic, and the search feature is automatic as well.  Introducing the concept of a category means that the user has to tell Paperless about this in some way -- in other words, it's the opposite direction of what I'm trying to achieve here.  We'd also have to add the category to the export somehow, which is already kinda scary (file names contain a timestamp, sender, title, and tags... all in the file name!)

I see what you're saying about categories and there's definitely value in an n:1 relationship vs. the n:n one currently represented in tags, but I'm not yet sold that this can be done without making Paperless more complicated than it needs to be.

I do however like the idea of attaching actions to a tag, but we'd need to flesh-out what those actions would look like.  As @the01 suggests, we could do to tags what you're suggesting we do to categories, and allow the user to attach a few (pre-defined?) actions: create a thumbnail, send an email, execute a script... whatever.

So @nuudles, are you committed to this idea of categories, or do you think we could cover your needs with something like an `Tag.actions` attribute?

**Comment by the01** [comment]
hmm..what if you could "save" searches...instead of "navigation", you'd have "favourites" (one or more tags).

I understand your arguments for categorization, but it's difficult to say something is clearly category A or cat  B. There are in my opinion no clear lines when it comes to scanned documents. (tax documents could come in the mail aswell :wink:).
That is why I suggested tags (back in #9)

**Comment by danielquinn** [comment]
I think the idea of saved searches and favourites is outside the scope of this issue, but I like your enthusiasm :-)

Tell you what, for now I'm happy to add this sort of thing to the backlog as "nice to haves" since they're not exactly required for everyday use (while having a proper logging facility, API, and UI clearly is).  I'm still not sold on categories, if for no other reason that the complicate the file naming for export.  The actions thing sounds interesting though and I'm happy to put that in the backlog.

**Comment by nuudles** [comment]
I completely understand the desire for simplicity and not overcomplicating things. It's hard because the project has such broad appeals that keeping things simple while maintaining the minimum viability for people is super hard.

That being said, I think if something like this were to be added, there's no reason it couldn't be completely optional and default to not being categorized at all.

The import/export filename issues continues to cause you grief, I can see, so I can understand not wanting to impose further complexities there, although one solution could be something like:

`[Category] Sender - Title - tag,tag,tag.pdf`

... Gross...

Anyway, I might be trying to use the project differently than your original intentions, so my hope was to see if others would be inclined to want the functionality. There's certainly nothing stopping me from maintaining a fork that includes it for my own use, if I so desire.

The Tag actions idea is pretty interesting and may end up solving my immediate want of something like thumbnails for each Document if they were appropriately Tagged, but does seem like it could get complicated rather quickly.

**Comment by the01** [comment]
@danielquinn: thanks, ideas were never my problem - its more about having the time to realize them all :wink:

@nuudles: You have to throw in a little timestamp as well

**Comment by danielquinn** [comment]
Square brackets thing would be a problem as is currently being discussed in [this very long issue](https://github.com/danielquinn/paperless/issues/51).  TL;DR: exported files end up on filesystems other than Linux, and special characters are a problem for dumb operating systems.

And please don't apologise for trying to do more with this project than was originally intended.   I wrote this thing for fun to solve a problem I was personally having and it's exploded into a full-blown project.  Now I'm trying to sail the waters of project management, trying to keep it useful to most people without bloating it and it's tough so I'm resistant to feature additions.

The truth is though, so long as we don't *require* any user interaction to scan & index a document, adding a category shouldn't hurt the process.  The real problem is the exporting and unfortunately the file name is getting really long.  If we do adopt categories, perhaps it would be best to have exports involve a list of files with the format `Sender - Title.extension` along with a separate `metadata.json` file for imports.  It would mean we'd have to write an importer separate from the current `document_consumer` process, but it would give us more lattitude regarding what kinds of metadata we would attach to the document.

So now I just grew the feature set from "lets add actions & categories" to include "a new importer".  This if fun!

Ok, let's say this:

> I'm ok with adding categories and actions, but they can't be added until we develop a means of importing documents *separate* from the standard consumption process because of this `metadata.json` thing.  And this has to come *after* the new logging code, and probably the API as well.  Of course if someone else were to write it, that would speed up the process :-)

Does that sound good?

**Comment by the01** [comment]
:+1:

**Comment by nuudles** [comment]
I think that sounds good. Is there a "Contributing" section or list of To-Dos in case I have some spare cycles to help move everything along? For instance, I might be able to help with building out the API.

**Comment by danielquinn** [comment]
Well for now, it's basically this issue queue.  I'll try to clean it up a bit and add some more explicit to-do's.  If you see something you'd like to contribute on, assign an issue to yourself just so I know not to fiddle with that.

**Comment by stgarf** [comment]
@nuudles Anything change over the last three years or so? I'm just going through old issues in the repo to see what can potentially be worked on still or cleaned up.

**Comment by nuudles** [comment]
@stgarf Ha! Thanks for checking in with me! I can't say any work has done by me as to this particular request, so I think it can be safely closed unless any other people have a hankering for it.

**Comment by stgarf** [comment]
Thanks @nuudles! Go ahead and close it out if you'd like (or someone'll get around to it)
